name: 🎁 New Perk Submission
description: Submit a new startup perk or credit program
title: "[PERK] Company Name - Program Name"
labels: ["new-perk", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a new perk! Please fill out the information below.
        
  - type: input
    id: company
    attributes:
      label: Company Name
      description: Official company name
      placeholder: e.g., Cloudflare
    validations:
      required: true

  - type: input
    id: program
    attributes:
      label: Program Name
      description: Official program name
      placeholder: e.g., Cloudflare for Startups
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does this perk belong to?
      options:
        - cloud
        - ai
        - database
        - analytics
        - infrastructure
        - security
        - saas
        - other
    validations:
      required: true

  - type: input
    id: credits
    attributes:
      label: Credit Value/Discount
      description: Specific credit amount or discount offered
      placeholder: e.g., Up to $100,000 in credits
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief 1-2 sentence description of the perk
      placeholder: What does this perk offer?
    validations:
      required: true

  - type: textarea
    id: eligibility
    attributes:
      label: Eligibility Requirements
      description: Who can apply for this perk?
      placeholder: e.g., Early-stage startups, YC companies, venture-backed, etc.
    validations:
      required: true

  - type: input
    id: apply-url
    attributes:
      label: Application URL
      description: Direct link to apply for this perk
      placeholder: https://
    validations:
      required: true

  - type: input
    id: source-url
    attributes:
      label: Source/Verification URL
      description: Link to official documentation or announcement
      placeholder: https://
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any other relevant information (optional)
      placeholder: Expiration dates, special requirements, etc.

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have verified this program is currently active
          required: true
        - label: I have tested the application URL and it works
          required: true
        - label: I have checked for duplicate entries
          required: true
        - label: The information provided is accurate to the best of my knowledge
          required: true
